fdnd-agency/atlas4045

static/global.css

Resolves #44 
Added some design tokens to allow for more consistent design across the entire website. These have not yet been applied to existing components, and thus these components should be refactored to use the new design tokens.

Added some design tokens to global.css

---

src/lib/organisms/Header.svelte

Resolves issue #47 
Added the eager loading rule on the Header logo for a more performant page loading experience.

Added eager loading rule on logo in Header

---

src/lib/atoms/Debug.svelte

Resolves issue #52 
Cleaned up some dead code from the debug component which was previously used to randomise the colour. This code is no longer used because the colour is now picked according to the colour palette, so that the debug component doesn't look as out of place when testing.

Cleaned up dead code from Debug component

---

src/lib/molecules/PosterCard.svelte
src/lib/organisms/PostersOverview.svelte
src/routes/+page.js

feat: show address floor or addition #101 :sparkles:

---

src/lib/atoms/DirectusImage.svelte
src/lib/molecules/PosterCard.svelte
src/lib/organisms/PostersOverview.svelte
src/routes/+page.server.js
svelte.config.js

Resolves issue #107 
Showing both portrait and landscape oriented cover images fully.

Feature portrait landscape cover images #107

---

src/lib/atoms/Button.svelte
src/lib/atoms/DirectusImage.svelte
src/lib/molecules/Logout.svelte
src/lib/molecules/PosterCard.svelte
src/lib/organisms/PosterIntroductie.svelte
src/lib/organisms/PostersOverview.svelte
static/global.css

Filled out grid and span landscape poster over multiple columns #107

feat: expanded layout #107

---

src/lib/atoms/Button.svelte
src/lib/molecules/FilterNaam.svelte
src/lib/molecules/FilterStraat.svelte
src/lib/organisms/PostersFilter.svelte

Added some more comments to the form code in preparation for giving a presentation on how to make PE forms using Svelte.

More comments in form code

---

src/lib/organisms/PostersFilter.svelte

Fixed a random character showing up in the filter component

Removed random character in Filter

---

src/routes/+page.svelte

feat: small tweak #171

---

src/routes/posters/[id]/+page.svelte

Worked on basic styling of the detailpage #159

feat: worked on basic sstyling #159

---

src/routes/+page.svelte

Resolves issue #1337
[livesite](https://livesite.com)

feat: worked on #171

---

src/routes/+page.svelte
static/global.css

Trying out blue background #171

feat: blue background maybe 💄

---

src/lib/atoms/Button.svelte
src/lib/atoms/PostersTitle.svelte
src/lib/molecules/Logout.svelte
src/lib/molecules/PosterCard.svelte
src/lib/organisms/PostersCarousel.svelte
src/lib/organisms/PostersFilter.svelte
src/lib/organisms/PostersOverview.svelte
src/routes/+page.svelte
src/routes/posters/+page.svelte
static/global.css

Several design tweaks 💄 
* Consistent hover & focus states
* Highlighted buttons
* Heading styling
* Feedback on filtered posters

feat: several design tweaks 💄

---

src/lib/molecules/PosterCard.svelte

feat: tweaking poster card states

---

src/lib/atoms/Button.svelte

feat: micro tweak

---

src/lib/atoms/Button.svelte

bug: fixed css bug

---

src/lib/molecules/FilterStraat.svelte
src/lib/molecules/PosterCard.svelte
src/lib/organisms/Header.svelte
src/lib/organisms/PostersCarousel.svelte
src/lib/organisms/PostersFilter.svelte
src/lib/organisms/PostersOverview.svelte
src/lib/utils/getCurrentPage.js
src/routes/+page.server.js
src/routes/+page.svelte
src/routes/adressen/+page.js
src/routes/adressen/+page.svelte
src/routes/adressen/[id]/+page.server.js
src/routes/adressen/[id]/+page.svelte
src/routes/gebeurtenissen/+page.svelte

Feature 187 events page

---

src/lib/atoms/PostersTitle.svelte
src/lib/organisms/Header.svelte
src/routes/+page.svelte

feat: small design tweaks

---

src/routes/+page.server.js

Showing random highlighted posters for now, make it possible for the content editors to pick highlighted posters or events by hand later

feat: showing random highlighted posters on the landingpage #193

---

package-lock.json
package.json
src/lib/organisms/Map.svelte
src/routes/adressen/+page.js
src/routes/adressen/+page.svelte

The map shows all address with latlong coordinates

feat: first version of a map on the address overview page #195

---

src/lib/organisms/Map.svelte
src/routes/adressen/+page.svelte
src/routes/gebeurtenissen/+page.svelte
static/assets/fonts/Fraunces/index.html
static/global.css

* Smaller map height for better usability on mobile
* removed console.logs
* fullwidth layouts

feat: worked on #196

---

src/lib/organisms/Map.svelte
src/routes/adressen/+page.svelte

When the addresses are filterde the map is refreshed without a page refresh

feat: refresh map with filtered addresses without page refresh #196

---

src/lib/organisms/Map.svelte
src/lib/utils/getCurrentPage.js

feat: cleaned up code #196

---

src/lib/organisms/Header.svelte

The logo image is now a link to the homepage instead of just an image
Resolves issue #235

feat: logo is now a link

---

src/lib/organisms/Map.svelte
src/routes/adressen/[id]/+page.server.js
src/routes/adressen/[id]/+page.svelte

Added map on detail page with individual map marker.
Resolves issue #239 
[livesite](https://livesite.com)
How it looked before:
How it looks now:
src > routes > adressen > [id] > page.svelte

Feature 239 map on detailpage

---

src/lib/organisms/Map.svelte
src/routes/adressen/+page.svelte
src/routes/adressen/[id]/+page.svelte

- zoom and view is now focus on the marker of the poster
- styling: map has blue border + h1 has a blue background for cohesie
Resolves issue #248

Feature 248 zoomlevel map detailpage

---

src/routes/+page.svelte

Fixed horizontally scrolling on homepage.
Resolves issue #244 
[livesite](https://livesite.com)
src > routes > +page.svelte

fix: fixed horizontal scrolling bug

---

src/lib/atoms/DirectusImage.svelte
src/lib/molecules/PosterCard.svelte

- Less border radius on poster (--border-radius-sm)
- Boxshadow was ugly so didn't do that afterall
Resolves issue #250
DirectusImage <-component

Feature 250 less border radius

---

src/lib/atoms/FilterChip.svelte
src/lib/molecules/ActiveFilters.svelte
src/lib/molecules/FilterSectionList.svelte
src/lib/organisms/SideFilter.svelte

Resolves issue #226 
Created chips at the top of the filter component which show active filters, and can be used to quickly disable them. Styling is subject to change, but the logic is finally working.

feat: #226 Active filter chips 🚧 

---

package-lock.json
src/lib/atoms/Checkbox.svelte
src/lib/atoms/FilterChip.svelte
src/lib/atoms/TextInput.svelte
src/lib/molecules/ActiveFilters.svelte
src/lib/molecules/FilterSearchbar.svelte
src/lib/molecules/FilterSectionList.svelte
src/lib/molecules/FilterSectionSearch.svelte
src/lib/organisms/SideFilter.svelte

Resolves issue #255
Improved some of the styling on the filter component. Can still be improved further according to the original design (like some dividers), but it is an improvement nonetheless.

feat: #255 Improved filter styling (WIP) 🚧 

---

src/lib/atoms/Checkbox.svelte
src/lib/atoms/FilterChip.svelte

Resolves issue #217
Added some hover and focus states to the checkbox component for better user experience and accessibility.

feat: #217 Checkbox hover + focus states

---

src/lib/organisms/SideFilter.svelte

Resolves issue #269 
Removed some non-working components from the filter, so that the filter in the release is stable.

feat: Removed non-working components from filter 🚸

---

src/lib/atoms/PostersTitle.svelte

- #277 
Made the PostersTitle dynamic again based on the currently selected filters to give the user more feedback when filters are active.

feat: Made PostersTitle dynamic based on filter 🚸

---

src/lib/atoms/PostersTitle.svelte

Tweaked colour in PostersTitle to be more neutral

feat: Tweaked colour in PostersTitle 💄

---

src/lib/molecules/FilterSectionList.svelte
src/lib/organisms/SideFilter.svelte

Resolves issue
- #270 
Changed filter copy text to better reflect the filter components available in the current release

feat: #270 - Improved filter copy

---

src/lib/atoms/PostersTitle.svelte
src/lib/atoms/TextInput.svelte
src/lib/molecules/FilterSearchbar.svelte
src/lib/organisms/SideFilter.svelte
src/routes/adressen/+page.js

Resolves issue 
- #274
Created a working search bar for searching by name, which automatically submits while typing and debounces requests.

feat: #274 - Working name searchbar

---

src/lib/molecules/PosterCard.svelte

Resolves issue
- #259
Added horizontal dashes to addresses which have a floor number, to make it clearer to the user that it is a floor number.

feat: #259 - Added horizontal dash to addresses 🚸

---

src/routes/+page.svelte
src/routes/adressen/+page.svelte
src/routes/adressen/[id]/+page.svelte

Resolves issue
- #303 
Added page titles in the head element, which were currently missing.

feat: Added page titles 🔍

---

src/lib/organisms/Header.svelte
src/lib/organisms/Map.svelte
src/lib/organisms/PostersCarousel.svelte
src/lib/organisms/PostersOverview.svelte
src/lib/organisms/SideFilter.svelte

- #316
Refactored components in the Organism folder. Mostly just removed dead code. Also refactored class declarations into the array form of [clsx](https://www.npmjs.com/package/clsx).

refactor: #316 - Organism components

---

src/lib/index.js
src/lib/organisms/Hero.svelte
src/lib/organisms/SuggestedPosters.svelte
src/routes/+page.svelte

- #322 
Refactored the home page. Took the hero section, and the suggested posters section, and moved them into separate components. This keeps the page lean and clear.

refactor: #322 - Home page
